version: '3'

services:
  # db_in_postgres:
  #   restart: always
  #   image: postgres:11-alpine
  #   environment:
  #     POSTGRES_USER: my_db_user
  #     POSTGRES_DB: my_db
  #     POSTGRES_PASSWORD: my_db_password
  #   volumes:
  #     - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
  db_in_mysql:
    restart: always
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'my_db'
      MYSQL_USER: 'my_db_user'
      MYSQL_PASSWORD: 'my_db_password'
      MYSQL_ROOT_PASSWORD: 'my_db_root_password'
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      GOPATH: /go
      APP_PORT: 80
      APP_ADAPTER_HTTP_ROUTER: gorilla_mux # Possible values: chi | gorilla_mux | julienschmidt_httprouter
      APP_ADAPTER_UUID_GENERATOR: gofrs_uuid # Possible values: google_uuid | gofrs_uuid (if blank: empty_uuid)
      APP_ADAPTER_DATABASE_DRIVER: mysql # Possible values: postgres | mysql
      DATABASE_HOST: db_in_mysql
      DATABASE_PORT: 3306
      DATABASE_NAME: my_db
      DATABASE_USER: my_db_user
      DATABASE_PASSWORD: my_db_password
    ports:
      - 3000:80
