version: '3'

services:
  db_in_postgres:
    restart: always
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: my_db_user
      POSTGRES_DB: my_db
      POSTGRES_PASSWORD: my_db_password
  db_in_mysql:
    restart: always
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'my_db'
      MYSQL_USER: 'my_db_user'
      MYSQL_PASSWORD: 'my_db_password'
      MYSQL_ROOT_PASSWORD: 'my_db_root_password'
  app:
    restart: always
    volumes:
      - ./:/app
    command: /bin/bash -c 'goose -allow-missing up && nodemon -L --ext "go,mod,sum" --exec "go run /app/cmd/web/main.go" --signal SIGTERM'
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      APP_PORT: 80
      GOOSE_MIGRATION_DIR: /app/internal/infra/database_migrations/goose
      APP_ADAPTER_LOGGER_LEVEL: info # Possible values: debug | info | warn | error
      APP_ADAPTER_LOGGER: zap # Possible values: standard | zap
      APP_ADAPTER_HTTP_ROUTER: gorilla_mux # Possible values: chi | gorilla_mux | julienschmidt_httprouter
      APP_ADAPTER_UUID_GENERATOR: gofrs_uuid # Possible values: google_uuid | gofrs_uuid (if blank: empty_uuid)
      APP_ADAPTER_DATABASE_DRIVER: mysql # Possible values: postgres | mysql
      GOOSE_DRIVER: mysql # Possible values: postgres | mysql
      GOOSE_DBSTRING: "my_db_user:my_db_password@tcp(db_in_mysql:3306)/my_db?parseTime=true&multiStatements=true" # Possible values: postgres (host=db_in_postgres port=5432 user=my_db_user password=my_db_password dbname=my_db sslmode=disable) | mysql (my_db_user:my_db_password@tcp(db_in_mysql:3306)/my_db?parseTime=true&multiStatements=true)
      DATABASE_HOST: "db_in_mysql"
      DATABASE_PORT: 3306
      DATABASE_NAME: my_db
      DATABASE_USER: my_db_user
      DATABASE_PASSWORD: my_db_password
      DATABASE_SSLMODE: disable
    ports:
      - 3000:80
